### ISSUE TITLE
Open Source Backstage Plugin

### ISSUE THREAD

**Issue by laceyallyn** [TeamTopologies/Team-API-template#6]
# Problem
Enabling organizations to adopt the Team Topologies philosophy and concepts despite differences in ways of working, tooling used for team / service / documentation management and discovery tooling.

# Suggested Solution
Build an Open Source Backstage Plugin for Teams (or contribute to the existing catalog entry for teams) integrating with catalog data for Team data and relationships with things the team owns like Components, Services (Applications), Domains, internal Tooling), DataSets & Machine Learning Projects, Documentation, etc., with a UI that makes it easy for teams to see the stakeholders of the things they own, as well as leadership and support staff of their team, and metadata like the team's purpose/mission, the type of customer they serve, link to their upcoming plans (i.e. roadmap), office hours signup, and preferred method of contact—with type classification that includes a tooltip linking to resources where people learn more about team topographies.
*note: thanks to backstage, maintenance of things the team owns/are responsible for and the stakeholders (of the things they own) can be (largely) automated via backstage assuming dependencies of those software assets are surfaced via the catalog.

### Context
[Backstage](https://backstage.io/) is a platform framework for building developer portal to centralize and democratize access to information, tooling, and resources in a consistent, beautiful, interoperable way—enabling not only developers, but also their stakeholders—to collaborate more fluidly because it's easier to discover whatever it is they are looking for.

At [Zalando](https://en.zalando.de/), we are aiming to integrate the entire experience for both Engineers and Analysts and their stakeholders (leadership, product, program, project management, designers, etc.). [I am the product manager](https://www.linkedin.com/in/lacey-allyn-nagel/) driving the initiative and would be happy to chat more about the topic if you're interested ☺️

**Comment by matthewskelton** [comment]
Hi @laceyallyn - good suggestion. It would be nice to point to your Backstage plugin from the Team API template repo here. 

What's your rough timeframe for getting the plugin done? If it's "soon", we'll keep this issue open, but if we're talking "years" then we might close this issue and just ask you to notify us when the plugin is ready. 

🙏

**Comment by laceyallyn** [comment]
I was actually suggesting that contributing (a new or to an existing) backstage plugin (which would basically be a shell UI for what you documented in the readme) yourself would be an excellent way to roll out (and embed) the concept of team topologies in the hundreds organizations already using backstage, or maybe just something to take into consideration about the market and how people might like to use the data in the bigger picture 🙂 

My goal in reaching out was to make you aware of Backstage (in case you weren't already) because Team data is just a small piece of the information that tech teams need to access and understand in order to collaborate effectively. Team data (and data about what they are responsible for, dependent on, or who their stakeholders are) is most valuable when automated as much as possible and fully integrated with other info, resources, and tooling, and not in a stand-alone doc site. 

We're currently working on improving the interoperability and automation around what teams own, contribute to, are dependent on, and who their stakeholders are, and on providing structure to define things like ways or working on a domain level instead of a team level, so I definitely wouldn't say this would be our goal in the short term.

**Comment by matthewskelton** [comment]
Hi @laceyallyn thanks for the clarification. Yep, we have used Backstage as an example of a tool that can be part of a good approach to flow-centric platforms. We are aware of several startups and SaaS tools that are using TT principles in ways like you suggest, so we are going to let the marketplace evolve a bit and see what emerges. 

Thank you for taking the time to describe the value!
